# Training/validation split
ntrain: 4000
nvalid: 500
ntest: 500

# Model architecture
nbasis: 686
encoder_hidden: [2048, 2048, 2048, 2048, 2048]
g_hidden: []

# Optimisation
batch_size: 100
sub: 1
learning_rate: 0.001
epochs: 7500
scheduler_step_size: 250
gamma: 0.9

# Activations
activation_encoder: relu
activation_g: identity

# Regularisation / constraints
lambda_in: 0.0
lambda_out: 0.6
lambda_sparse: 0.0
lambda_inv: 0.0
lambda_op: 1.0

k_iterate: 2
random_seed: 42

base_path: /cat_map/data/conjugated/Conjugated_TO_JAX-5000fs-100ps-4or-k2

# Runtime
model_name: SABON
device: cuda
