# Training/validation split
ntrain: 3000
nvalid: 500
ntest: 500

# Model architecture
nbasis: 225
encoder_hidden: [2048, 2048, 2048, 2048, 2048]
g_hidden: []

# Optimisation
batch_size: 100
sub: 1
learning_rate: 0.001
epochs: 4500
scheduler_step_size: 250
gamma: 0.9

# Activations
activation_encoder: relu
activation_g: identity

# Regularisation / constraints
lambda_in: 0.0
lambda_out: 0.0
lambda_sparse: 0.0
lambda_inv: 0.0
lambda_op: 1.0

# Data augmentation
linear_augment: false
linear_augment_percentage: 0.6
random_seed: 1

base_path: /srv/scratch/z5547452/data_cat_map/TO_perturbed_cat_map_4D-4000fs-100ps-5or

# Runtime
model_name: SABON
device: cuda
